apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: amq-streams
spec:
  kafka:
    replicas: 1
    config:
      auto.create.topics.enable: true
      default.replication.factor: 1
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
      inter.broker.protocol.version: "3.6"
    authorization:
      type: simple
      superUsers:
      - CN=maestro-kafka-admin
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - authentication:
        type: tls
      name: tls
      port: 9093
      tls: true
      type: route
    storage:
      type: ephemeral
    version: 3.6.0
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
